### PR TITLE
bump version to rebuild against xorg-libx11=1.7.2

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
the current package requires `xorg-libx11=1.6` even though verison `1.7.2` is available. This PR just increments the build number and re-renders to trigger a rebuild against the most recent dependencies.

**Comment by zklaus** [comment]
Thanks, @izahn! Feels like this should have been called by a migrator, doesn't it? Is there something we should do to make that happen for the next time xorg-xlib gets bumped?

**Comment by izahn** [comment]
> Thanks, @izahn! Feels like this should have been called by a migrator, doesn't it? Is there something we should do to make that happen for the next time xorg-xlib gets bumped?

It does feel that way, but this is an area of conda-forge I haven't learned much about yet. I'll try to find time to look into it.

**Comment by zklaus** [comment]
Thanks, @izahn. Any pointers on this, @conda-forge/core? Perhaps we should add xorg and/or xorg/xlib11 to the global pinning at https://github.com/conda-forge/conda-forge-pinning-feedstock?

**Pull request merged**
